# Generated by Django 2.2.16 on 2022-06-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='genrestitles',
            options={'verbose_name_plural': 'Жанры - произведения'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name_plural': 'Произведения'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Пользователи'},
        ),
    ]
